build:

	gcc -Wall -g -o ext2_cp ext2_cp.c

	gcc -Wall -g -o ext2_rm ext2_rm.c

	gcc -Wall -g -o ext2_ln ext2_ln.c

	gcc -Wall -g -o ext2_mkdir ext2_mkdir.c

clean:
	rm -f ext2_cp ext2_rm ext2_ln ext2_mkdir
